# Generated by Django 4.0 on 2022-09-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contactno', models.CharField(max_length=15)),
                ('aadharno', models.CharField(max_length=12)),
                ('noofpacket', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('totalamt', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('restamt', models.IntegerField()),
                ('bookingdate', models.CharField(max_length=30)),
            ],
        ),
    ]
