# Generated by Django 4.0 on 2022-09-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='aadharno',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
